### ISSUE TITLE
System.NullPointerException. Argument 1 Can't be null. Line 263, Col1

### ISSUE THREAD

**Issue by pradeepkumargali** [natewallace/ApexNTLM#2]
Hi Nate,

I am executing below code. 

HTTPRequest r = new HTTPRequest();
string endpointurl = 'zzzzzzz';
r.setEndpoint(endpointurl);
r.setMethod('GET');

HttpClient client = new HttpClient(xxxx,xxxx);
HTTPResponse res = client.send(r);
System.debug(res.getBody());

it says, 
**System.NullPointerException. Argument 1 Can't be null. Line 263, Col1**

Using API 34.0.

I added the url in remote site settings. Any help?

Regards,
Pradeep

**Comment by pradeepkumargali** [comment]
I figured out that Line 196 was causing the problem HttpClient.apxc. 

_req.setBodyAsBlob(request.getBodyAsBlob());_

Now, the request returns 302 :(

**Comment by natewallace** [comment]
I'm not sure I can help with this issue.  A 302 is a redirect sent from the server.  If your server is on a private network it may be why it's bouncing your request.  I would test and make sure that the server you are trying to communicate with is accessible from the internet.

**Comment by pradeepkumargali** [comment]
Thanks Nate! I figured it out. Our firewall is redirecting HTTP to HTTPS.

**Comment by dseligson** [comment]
Pradeep, I was seeing the exact same problem and we don't have HTTPS, just HTTP.
My solution was to change that line with:
req.setBodyDocument(request.getBodyDocument()); 
and it worked fine afterwards.   Must be something weird with the way Blobs are returned, but the Document format worked perfectly in this application.  I also used that for debugging with:
System.debug(request.getBodyDocument().toXmlString() );  //Prints whole XML Doc

**Comment by natewallace** [comment]
FYI, I wouldn't recommend exposing a service that uses NTLM authentication over http.  NTLM has some security vulnerabilities you would most likely not want to expose over a non https connection.

**Comment by dseligson** [comment]
Thanks Nate, I completely agree with you.  I'm already guiding them towards adding an SSL connection.   But, still, you're integration is wonderful.
